// Generated by impulse-graph-spec codegen tool (v2.4.0). DO NOT EDIT MANUALLY.
package org.impulsegraph.spec.v2_4;

java.lang.foreign.*;
import java.lang.invoke.VarHandle;

/**
 * Java 25 Foreign Function & Memory (FFM) Layouts for Impulse Graph Binary Snapshot Spec v2.4.0.
 */
public final class ImpulseLayoutsV2_4 {
    private ImpulseLayoutsV2_4() {}

    public static final int SPEC_VERSION_MAJOR = 2;
    public static final int SPEC_VERSION_MINOR = 4;
    public static final int SPEC_MAGIC = 0x494D5053;
    public static final int HEADER_BASELINE_OFFSET = 4096;

    /** Section 1 Fixed 4KB Baseline Snapshot Header (Size: 1096 Bytes) */
    public static final StructLayout IMPULSE_SNAPSHOT_HEADER_V2_4_T_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_INT_UNALIGNED.withName("magic"),
        ValueLayout.JAVA_SHORT_UNALIGNED.withName("version"),
        ValueLayout.JAVA_INT_UNALIGNED.withName("data_offset"),
        ValueLayout.JAVA_SHORT_UNALIGNED.withName("domain_count"),
        ValueLayout.JAVA_SHORT_UNALIGNED.withName("relation_count"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("kafka_offset"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("timestamp_ms"),
        MemoryLayout.sequenceLayout(32, ValueLayout.JAVA_BYTE).withName("sha256"),
        MemoryLayout.sequenceLayout(2, ValueLayout.JAVA_BYTE).withName("reserved"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("global_required_features")
    ).withName("impulse_snapshot_header_v2_4_t");

    public static final VarHandle VH_IMPULSE_SNAPSHOT_HEADER_V2_4_T_MAGIC =
        IMPULSE_SNAPSHOT_HEADER_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("magic"));
    public static final VarHandle VH_IMPULSE_SNAPSHOT_HEADER_V2_4_T_VERSION =
        IMPULSE_SNAPSHOT_HEADER_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("version"));
    public static final VarHandle VH_IMPULSE_SNAPSHOT_HEADER_V2_4_T_DATA_OFFSET =
        IMPULSE_SNAPSHOT_HEADER_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("data_offset"));
    public static final VarHandle VH_IMPULSE_SNAPSHOT_HEADER_V2_4_T_DOMAIN_COUNT =
        IMPULSE_SNAPSHOT_HEADER_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("domain_count"));
    public static final VarHandle VH_IMPULSE_SNAPSHOT_HEADER_V2_4_T_RELATION_COUNT =
        IMPULSE_SNAPSHOT_HEADER_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("relation_count"));
    public static final VarHandle VH_IMPULSE_SNAPSHOT_HEADER_V2_4_T_KAFKA_OFFSET =
        IMPULSE_SNAPSHOT_HEADER_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("kafka_offset"));
    public static final VarHandle VH_IMPULSE_SNAPSHOT_HEADER_V2_4_T_TIMESTAMP_MS =
        IMPULSE_SNAPSHOT_HEADER_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("timestamp_ms"));
    public static final VarHandle VH_IMPULSE_SNAPSHOT_HEADER_V2_4_T_GLOBAL_REQUIRED_FEATURES =
        IMPULSE_SNAPSHOT_HEADER_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("global_required_features"));

    /** Section 2 Relation Directory Metadata Entry (Size: 109 Bytes) */
    public static final StructLayout IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_SHORT_UNALIGNED.withName("src_domain_id"),
        ValueLayout.JAVA_SHORT_UNALIGNED.withName("tgt_domain_id"),
        ValueLayout.JAVA_BYTE.withName("encoding_type"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("node_count"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("edge_count"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("section_features"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("csr_row_off_offset"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("csr_row_off_bytes"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("csr_col_idx_offset"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("csr_col_idx_bytes"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("id_map_offset"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("id_map_bytes"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("dto_lookup_offset"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("dto_lookup_bytes"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("delta_log_offset"),
        ValueLayout.JAVA_LONG_UNALIGNED.withName("delta_log_bytes")
    ).withName("impulse_relation_directory_entry_v2_4_t");

    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_SRC_DOMAIN_ID =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("src_domain_id"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_TGT_DOMAIN_ID =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("tgt_domain_id"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_ENCODING_TYPE =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("encoding_type"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_NODE_COUNT =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("node_count"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_EDGE_COUNT =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("edge_count"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_SECTION_FEATURES =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("section_features"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_CSR_ROW_OFF_OFFSET =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("csr_row_off_offset"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_CSR_ROW_OFF_BYTES =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("csr_row_off_bytes"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_CSR_COL_IDX_OFFSET =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("csr_col_idx_offset"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_CSR_COL_IDX_BYTES =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("csr_col_idx_bytes"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_ID_MAP_OFFSET =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("id_map_offset"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_ID_MAP_BYTES =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("id_map_bytes"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_DTO_LOOKUP_OFFSET =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("dto_lookup_offset"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_DTO_LOOKUP_BYTES =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("dto_lookup_bytes"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_DELTA_LOG_OFFSET =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("delta_log_offset"));
    public static final VarHandle VH_IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_DELTA_LOG_BYTES =
        IMPULSE_RELATION_DIRECTORY_ENTRY_V2_4_T_LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("delta_log_bytes"));

}