name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set Release Version from Tag
        run: |
          RAW_TAG="${{ github.ref_name }}"
          CLEAN_VERSION="${RAW_TAG#v}"
          mvn versions:set -DnewVersion=$CLEAN_VERSION -DgenerateBackupPoms=false

      - name: Publish artifacts
        run: mvn deploy -P release -DskipTests=true --batch-mode --errors
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PHASSPHRASE }}

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '**/target/*.jar'
